version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "833:80"
    depends_on: 
      - redis
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d/
      - ./nginx/var/log:/var/log/nginx
      - ./nginx/var/run:/var/run/
      - ./nginx/html:/usr/share/nginx/html/

  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis