version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "60000:80"
    depends_on: 
      - redis
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d/
      - ./nginx/var/log:/var/log/nginx
      - ./nginx/var/run:/var/run/
      - ./nginx/html:/usr/share/nginx/html/

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    restart: always
    ports:
      - "60001:80"
      - "60002:22"
      - "60003:443"
    volumes:
      - ./gitlab/conf:/etc/gitlab
      - ./gitlab/data:/var/opt/gitlab
      - ./gitlab/logs:/var/log/gitlab
